---
application:
  name: "programming-langugages-api"
  project: "programming-language-api"
  organization: "QoveryCommunity"
routers:
- name: "main-programming-langugages-api"
  routes:
  - application_name: "programming-langugages-api"
    paths:
    - "/*"
